//
// Created by sutil on 29/12/16.
//

#ifndef PROJETOU_TERMINAIS_H
#define PROJETOU_TERMINAIS_H

#define LOGICALVALUE_TRUE "true"
#define LOGICALVALUE_FALSE "false"
#define ARITHMETIOPERATOR_MAIS "+"
#define ARITHMETIOPERATOR_MENOS "-"
#define ARITHMETIOPERATOR_VEZES "*"
#define ARITHMETIOPERATOR_DIVIDIR "/"






#endif //PROJETOU_TERMINAIS_H
